---
  - name: "PLAY 1 - SENDING SHOW COMMANDS TO IOS DEVICES"
    hosts: "iosxe"
    connection: "network_cli"
    gather_facts: no
    tasks:

    - name: "TASK 1 - SEND A SINGLE ENABLE LEVEL SHOW COMMAND"
      cisco.ios.ios_command:
        commands: "show version"

    - name: "TASK 2 - SEND MULTIPLE ENABLE LEVEL SHOW COMMAND"
      cisco.ios.ios_command:
        commands:
        - "show ip interface brief"
        - "show interfaces"
        - "dir"

    - name: "TASK 3 - RUN AND PARSE COMMAND WITH NTC_TEMPLATES"
      ansible.utils.cli_parse:
        command: show ip interface brief
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: interfaces_ntc
      # sample output
      # interfaces_ntc:
      # - intf: GigabitEthernet1
      #   ipaddr: 10.10.20.181
      #   proto: up
      #   status: up

    - name: "TASK 1: PRINT DEBUG MAGIC VARIABLES FOR IOS"
      ansible.builtin.debug:
        var: interfaces_ntc

    - name: "TASK 1: PRINT DEBUG MAGIC VARIABLES FOR NXOS"
      debug:
        msg: "The first interface is {{ interfaces_ntc[0]['intf'] }} with an IP Address of {{ interfaces_ntc[0]['ipaddr'] }}"

    - name: "TASK 4 - RUN AND PARSE COMMAND WITH NTC_TEMPLATES"
      ansible.utils.cli_parse:
        command: show ip interface brief
        parser:
          name: ansible.netcommon.pyats
        set_fact: interfaces_pyats

    - name: "TASK : PRINT DEBUG MAGIC VARIABLES FOR IOS"
      ansible.builtin.debug:
        var: interfaces_pyats