
---
  - name: "PLAY 1 - REMOVE CONFIG FROM DEMO"
    hosts: "iosxe"
    connection: "network_cli"
    gather_facts: no
    tasks:
        - name: "TASK 1 - REMOVE CDP AND LLDP"
          cisco.ios.ios_config:
            lines:
                - "no cdp run"
                - "no lldp run"

        - name: "TASK 2 - REMOVE INTERFACES AND ACL"
          cisco.ios.ios_config:
            lines:
                - "no interface Loopback1337"
                - "no interface Loopback124"
                - "no interface Loopback125"
                - "no interface Loopback1450"
                - "no ip access-list extended test"

