# include looping / conditional / filter
---
  - name: "PLAY 1 - TBD"
    hosts: "routers"
    connection: "network_cli"
    gather_facts: no
    tasks:

      - name: "TASK 1 - ENSURE CONFIG DIR EXISTS"
        ansible.builtin.file:
          path: "config"
          state: "directory"
          mode: 0775
        run_once: true

      - name: "TASK 2 - BUILD IOS INTERFACE CONFIG"
        ansible.builtin.template:
          src: "ios_interface_lstrip.j2"
          dest: "config/{{ inventory_hostname }}_interface_config_lstrip.txt"