# no site code variable

snmp:
  ro: "internet_rtr01_ro"
  rw: "internet_rtr01_rw"
  contact: "internet_rtr01_contact"
  location: "internet_rtr01_location"

interfaces:
  - name: Loopback200
    description: "Loopback for NYC lab"
    ipv4addr: "10.223.223.100"
    subnet: "255.255.255.255"
  - name: Loopback201
    description: "Loopback for NYC lab"
    ipv4addr: "10.223.223.101"
    subnet: "255.255.255.255"
  - name: Loopback202
    description: "Loopback for NYC lab"
    ipv4addr: "10.223.223.102"
    subnet: "255.255.255.255"
  - name: Loopback203
    description: "Loopback for NYC lab"
    ipv4addr: "10.223.223.103"
    subnet: "255.255.255.255"
  - name: Loopback204
    description: "Loopback for NYC lab"
    ipv4addr: "10.223.223.104"
    subnet: "255.255.255.255"